include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - always_use_package_imports
    - combinators_ordering
    - directives_ordering
    - require_trailing_commas
    - sort_constructors_first
    - discarded_futures
    - eol_at_end_of_file
    - always_declare_return_types
    - always_put_control_body_on_new_line
