include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - always_use_package_imports
    - combinators_ordering
    - directives_ordering
    - require_trailing_commas
    - sort_constructors_first
