name: beamer_inner_router_test
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  beamer: ^1.6.1
  flutter:
    sdk: flutter
  flutter_rearch: ^1.6.8
  rearch: ^1.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
